version: '3.8'

services:
  ipfs-node1:
    image: ipfs/kubo:latest
    container_name: ipfs-node1
    ports:
      - "4001:4001"  # IPFS swarm
      - "5001:5001"  # IPFS API
      - "8080:8080"  # IPFS Gateway
    volumes:
      - ./ipfs-data-1:/data/ipfs
      - ./ipfs-staging-1:/export
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    command: ["daemon", "--migrate=true", "--enable-pubsub-experiment"]

  ipfs-node2:
    image: ipfs/kubo:latest
    container_name: ipfs-node2
    ports:
      - "4002:4001"  # IPFS swarm
      - "5002:5001"  # IPFS API
      - "8081:8080"  # IPFS Gateway
    volumes:
      - ./ipfs-data-2:/data/ipfs
      - ./ipfs-staging-2:/export
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data/ipfs
    command: ["daemon", "--migrate=true", "--enable-pubsub-experiment"]